/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ImgKit: typeof import('./src/components/toolkits/ImgKit.vue')['default']
    Pic: typeof import('./src/components/common/Pic.vue')['default']
  }
}
